root: true

overrides:
  - files: ['*.ts', '*.tsx']
    extends:
      - pegasus
      - pegasus/typescript
    parserOptions:
      project: tsconfig.json
    settings:
      react:
        version: detect
    rules:
      prefer-named-capture-group: off
      complexity: off
    env:
      browser: true
      jest: true

  - files: '*.js'
    extends:
      - pegasus
      - pegasus/node
