root: true
extends: airbnb
rules:
  class-methods-use-this: off
  no-underscore-dangle: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
  import/no-extraneous-dependencies: off
  no-console: off
  react/prefer-stateless-function:
    - error
    - ignorePureComponents: true
  react/no-multi-comp: off
  react/jsx-fragments:
    - error
    - element
  max-len:
    - error
    - code: 120
  quote-props:
    - error
    - consistent
  no-await-in-loop: off

env:
  jest: true
  browser: true
