root: true

overrides:
  - files: ['*.ts', '*.tsx']
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - 'eslint:recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:react/recommended'
      - 'plugin:react-hooks/recommended'
      - 'pegasus'

    env:
      browser: true
      jest: true

  - files: '*.js'
    extends:
      - 'airbnb-base'
      - 'pegasus'
    rules:
      no-console: off
      import/no-extraneous-dependencies: off
    env:
      node: true
